version: "3.9"
services:
  api-gateway:
    container_name: api-gateway
    image: nginx
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: clientes_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    restart: on-failure
    build: ./gateway
    ports:
      - "8000:80"
    depends_on:
      - clientes-service

  clientes-service:
    container_name: clientes-api
    build: ./clientes-service
    restart: always
    depends_on:
      - db
      - caching-db

  db:
    container_name: clientes-db
    image: postgres
    restart: always
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clientes_db
    ports:
      - 5432:5432
    expose:
      - 5432

  caching-db:
    container_name: redis-caching
    image: redis
    restart: always
    
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5454:5454/tcp
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=5454