CREATE TABLE IF NOT EXISTS CLIENTE(
    ID_CLIENTE INTEGER NOT NULL,
    NOME_CLIENTE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS EXTRATO(
    ID_EXTRATO SERIAL NOT NULL,
    SALDO INTEGER NOT NULL,
    DATA_EXTRATO DATE NOT NULL, 
    LIMITE INTEGER NOT NULL,
    CLIENTE  INTEGER NOT NULL,
    CONSTRAINT PK_EXTRATO PRIMARY KEY (ID_EXTRATO),
	CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT UQ_EXTRATO_CLIENTE UNIQUE (ID_EXTRATO, CLIENTE),
    CONSTRAINT CHK_EXTRATO CHECK (SALDO + LIMITE >= 0),
	CONSTRAINT CHK_LIMITE CHECK (LIMITE >= 0)
);

CREATE TYPE  TIPO_TRANSACAO AS ENUM ('C', 'D');
CREATE TABLE IF NOT EXISTS TRANSACAO
(
    ID_TRANSACAO SERIAL NOT NULL,
    VALOR INTEGER NOT NULL,
    TIPO TIPO_TRANSACAO NOT NULL,
    DESCRICAO TEXT NOT NULL,
    CLIENTE INTEGER NOT NULL,
    DATA_TRANSACAO TIMESTAMP NOT NULL, 
    CONSTRAINT PK_TRANSACAO PRIMARY KEY (ID_TRANSACAO), 
    CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE) 
        REFERENCES CLIENTE (ID_CLIENTE) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX TRANSACAO_CLIENTE_ID ON TRANSACAO (CLIENTE);
CREATE INDEX TRANSACAO_DATA ON TRANSACAO (DATA_TRANSACAO);

CREATE OR REPLACE PROCEDURE DEBITO(CLIENTE_TRANSACAO INT, SALDO_D INT, DESCRICAO_D TEXT) AS $$
DECLARE
    SALDO INTEGER; -- Adjust the data type as per your requirement
    LIMITE_CLIENTE INTEGER;
BEGIN
    -- Assigning the result of the query to the variable 'saldo'
    SELECT EXTRATO.SALDO, EXTRATO.LIMITE
    INTO SALDO, LIMITE_CLIENTE
    FROM EXTRATO
    WHERE CLIENTE_TRANSACAO = CLIENTE 
    ORDER BY DATA_EXTRATO DESC
    LIMIT 1;
    INSERT INTO EXTRATO(SALDO, DATA_EXTRATO, LIMITE, CLIENTE)
    VALUES (SALDO - SALDO_D, NOW(), LIMITE_CLIENTE, CLIENTE_TRANSACAO); 

    INSERT INTO TRANSACAO (CLIENTE, VALOR, TIPO, DATA_TRANSACAO, DESCRICAO)
    VALUES (CLIENTE_TRANSACAO, SALDO_D, 'D', NOW(), DESCRICAO_D);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE PROCEDURE CREDITO(CLIENTE_TRANSACAO INT, SALDO_C INT, DESCRICAO_C TEXT) AS $$
DECLARE
    SALDO INTEGER; -- Adjust the data type as per your requirement
    LIMITE_CLIENTE INTEGER;
BEGIN
    -- Assigning the result of the query to the variable 'saldo'
    SELECT EXTRATO.SALDO, EXTRATO.LIMITE
    INTO SALDO, LIMITE_CLIENTE
    FROM EXTRATO
    WHERE CLIENTE_TRANSACAO = CLIENTE 
    ORDER BY DATA_EXTRATO DESC
    LIMIT 1;
    INSERT INTO EXTRATO(SALDO, DATA_EXTRATO, LIMITE, CLIENTE)
    VALUES (SALDO + SALDO_C, NOW(), LIMITE_CLIENTE, CLIENTE_TRANSACAO); 

    INSERT INTO TRANSACAO (CLIENTE, VALOR, TIPO, DATA_TRANSACAO, DESCRICAO)
    VALUES (CLIENTE_TRANSACAO, SALDO_C, 'C', NOW(), DESCRICAO_C);
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE PROCEDURE NOVO_CLIENTE(CLIENTE_NOVO INT,  NOME_CLIENTE VARCHAR(50),  LIMITE_CLIENTE INT ) AS $$
BEGIN
    INSERT INTO  CLIENTE (ID_CLIENTE, NOME_CLIENTE)
    VALUES (CLIENTE_NOVO, NOME_CLIENTE);

    INSERT INTO EXTRATO(SALDO, DATA_EXTRATO, LIMITE, CLIENTE)
    VALUES (0, NOW(), LIMITE_CLIENTE, CLIENTE_NOVO); 
END;
$$ LANGUAGE plpgsql;


CALL NOVO_CLIENTE (1, 'ZE NGM', 100000);
CALL NOVO_CLIENTE(2, 'MARIA NGM', 80000);
CALL NOVO_CLIENTE(3, 'JOAO NGM', 242142);
CALL NOVO_CLIENTE(4, 'CHICO NGM', 153532);

CALL CREDITO(1, 1000, 'DESCRICAO')